server:
  port: 7903
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: micro-server-provider-user1
logging:
  level:
    root: INFO
    org.hibernate: INFO
eureka:
  client:
    service-url:
      defaultZone: http://chenlei:chenlei123@localhost:8761/eureka
  healthcheck:
    enabled: true
  instance:
    prefer-ip-address: true